name: dunkin_connect
main: fr.yannlm29.Plugin
version: 0.0.1
api-version: 1.15
commands:
   getPlayers:
      description: Get plauers data info
      usage: /<command>
   setBase:
      description: Set the coordinates of your base
      usage: /<command>